name: Build and Release

on:
  push:
    branches:
      - master   # 如果你的默认分支是 master，就改成 master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build (aarch64-linux-android)
        run: |
          ndk="$($ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
                 --list_installed | sed -E 's/( +[|] +)/|/g;s/ +$//' | \
                 grep '^  ndk' | cut -d '|' -f 4 | sort | head -n1)"
          ANDROID_NDK_HOME="$ANDROID_HOME/$ndk" ./build
        env:
          TARGET: aarch64-linux-android

      - name: Collect binaries
        run: |
          mkdir output
          cp dropbear/dropbear output
          cp dropbear/dbclient output
          cp dropbear/dropbearkey output
          cp dropbear/dropbearconvert output
          cp dropbear/scp output
          cp dropbear/LICENSE output/LICENSE.txt

      - name: Package zip
        run: zip --junk-paths dropbear-aarch64-linux-android.zip output/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: "Dropbear aarch64 Build ${{ github.run_number }}"
          body: "Automated aarch64-linux-android build for commit ${{ github.sha }}"
          files: dropbear-aarch64-linux-android.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
